version: '3.9'

services:
  dotnetservice:
    build:
      context: GrpcServiceApp/
      dockerfile: GrpcServiceApp/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - ASPNETCORE_URLS=http://+:3001
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build: src/web/career-pulse/
    ports:
      - "3030:3030"
